---
- name: "Ensure dependencies are installed"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ mariadb_install['dependencies']['RedHat'] }}"

- name: "Add repo for RedHat"
  block:
    - name: "Import MariaDB gpg key"
      ansible.builtin.rpm_key:
        key: "{{ mariadb_const[ansible_os_family]['mariadb_gpg'] }}"
        state: present

    - name: "Add MariaDB repository"
      ansible.builtin.yum_repository:
        name: mariadb
        description: Mariadb YUM repo
        baseurl: "{{ mariadb_const[ansible_os_family]['mariadb_repo'] }}"
        gpgcheck: yes
        enabled: true
        module_hotfixes: true
  when: mariadb.repo == "mariadb"

- name: "Install MariaDB packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  ignore_errors: true
  with_items: "{{ mariadb_install['packages']['RedHat'] }}"