---
- name: "Ensure dependencies are installed"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ mariadb_install['dependencies']['Debian'] }}"

- name: "Add repo MariaDB"
  block:
    - name: "Add MariaDB repository gpg key"
      ansible.builtin.apt_key:
        url: "{{ mariadb_const[ansible_os_family]['mariadb_gpg'] }}"
        state: present

    - name: "Add MariaDB repository"
      ansible.builtin.apt_repository:
        repo: "{{ mariadb_const[ansible_os_family]['mariadb_repo'] }}"
        state: present
  when: mariadb.src == "third_party"

- name: "Install MariaDB packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  ignore_errors: true
  with_items: "{{ mariadb_install['packages']['Debian'] }}"