---
- name: Converge
  hosts: all
  
  pre_tasks:
  - name: Unnessessary command
    ansible.builtin.shell:
      cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0
  
  vars:
    merge:
      mariadb:
        enabled: true
        version: "10.6"
      mariadb_install:
        enabled: true
      mariadb_repo:
        enabled: true      
  
  tasks:
    - name: include role mariadb
      include_role: 
        name: darexsu.mariadb