---
- name: manage database
  community.mysql.mysql_db:
    login_user: "{{ mariadb_actions__login_user }}"
    login_password: "{{ mariadb_actions__login_password }}"
    name: "{{ item }}"
    state: "{{ mariadb_actions__database_manage__state }}"
    encoding: "{{ mariadb_actions__database_manage__encoding }}"
    login_unix_socket: "{{ mariadb_actions__login_unix_socket }}"
    collation: "{{ mariadb_actions__database_manage__collation }}"
  with_items: "{{ mariadb_actions__database_manage__name }}"
  when: mariadb_actions__database_manage

- name: import sql
  community.mysql.mysql_db:
    login_user: "{{ mariadb_actions__login_user }}"
    login_password: "{{ mariadb_actions__login_password }}"
    name: "{{ item }}"
    state: "import"
    target: "{{ mariadb_actions__database_import_sql__path }}"
    encoding: "{{ mariadb_actions__database_import_sql__encoding }}"
    login_unix_socket: "{{ mariadb_actions__login_unix_socket }}"    
  with_items: "{{ mariadb_actions__database_import_sql__namedb }}"
  when: mariadb_actions__database_import_sql

- name: query to "{{ mariadb_actions__database_query__namedb }}"
  community.mysql.mysql_query:
    login_user: "{{ mariadb_actions__login_user }}"
    login_password: "{{ mariadb_actions__login_password }}"
    login_unix_socket: "{{ mariadb_actions__login_unix_socket }}"
    login_db: "{{ mariadb_actions__database_query__namedb }}"
    query: "{{ mariadb_actions__database_query__sql }}"
  when: mariadb_actions__database_query
  register: mariadb_query_response

- name: show query response
  debug:
    var: mariadb_query_response
  when: mariadb_actions__database_query__show_response

- name: manage user
  community.mysql.mysql_user:
    login_user: "{{ mariadb_actions__login_user }}"
    login_password: "{{ mariadb_actions__login_password }}"
    name: "{{ mariadb_actions__user__name }}"
    password: "{{ mariadb_actions__user__password }}"
    priv: "{{ mariadb_actions__user__privileges }}"
    state: "{{ mariadb_actions__user__state }}"
    encrypted: "{{ mariadb_actions__user__hashed_password }}"
    login_unix_socket: "{{ mariadb_actions__login_unix_socket }}"
  when: mariadb_actions__user

- name: dump database
  community.mysql.mysql_db:
    login_user: "{{ mariadb_actions__login_user }}"
    login_password: "{{ mariadb_actions__login_password }}"
    name: "{{ item }}"
    state: "dump"
    target: "{{ mariadb_actions__database_dump__folder }}dump_{{ item }}.sql"
    encoding: "{{ mariadb_actions__database_dump__encoding }}"
    login_unix_socket: "{{ mariadb_actions__login_unix_socket }}"
  with_items: "{{ mariadb_actions__database_dump__name }}"
  when: mariadb_actions__database_dump

- name: manage role "{{ mariadb_actions__role__name }}"
  community.mysql.mysql_role:
    login_user: "{{ mariadb_actions__login_user }}"
    login_password: "{{ mariadb_actions__login_password }}"
    name: "{{ mariadb_actions__role__name }}"
    state: "{{ mariadb_actions__role__state }}"
    login_unix_socket: "{{ mariadb_actions__login_unix_socket }}"
  when: mariadb_actions__role